spring:
  application:
    name: irmandade-backend-kotlin
  datasource:
    hiraki:
      ## connection pool
      connectionTimeout: 20000
      maximumPoolSize: 10
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
api:
  security:
    token:
      secret: my-secret